### ISSUE TITLE
custom transition

### ISSUE THREAD

**Issue by mentaman** [dor6/SingularComponent#3]
Right now the transition is always
```
            const scaleX = valueFormula((startingRect.width/targetRect.width), 1);
            const scaleY = valueFormula((startingRect.height/targetRect.height), 1);
            const translateX = valueFormula((startingRect.left - targetRect.left), 0);
            const translateY = valueFormula((startingRect.top - targetRect.top), 0);


            animationElement.style.left = `${targetRect.left}px`;
            animationElement.style.top = `${targetRect.top}px`;
            animationElement.style.width = `${targetRect.width}px`;
            animationElement.style.height = `${targetRect.height}px`;
            animationElement.style.transform = `translate(${translateX}px,${translateY}px) scale(${scaleX},${scaleY})`;
```

Its just changing the rect according to the easing function.
It would be nice letting the developers more power with a function they give on props.
and keeping the current behaviour as default.
If they want to make more customable transition. changing the width differently, or changing the color too and etc..

**Comment by dor6** [comment]
Instead how about using transform for the x and y, and using getComputedStyle and addressing the relevant css attributes that can affect size, attributes such as width height font-size and paddings. That way you can later on address attributes such as color.
